# Generated by Django 2.1.1 on 2018-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180916_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
