# Generated by Django 2.1.1 on 2018-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pantryitem_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitemline',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='category',
            field=models.CharField(choices=[('UC', 'UNCATEGORIZED'), ('GS', 'GENRAL_STOCK'), ('CANS', 'CANS'), ('BR', 'BREAKFAST'), ('SAV', 'SAVORIES'), ('SW', 'SWEETS'), ('SN', 'SNACKS'), ('SP', 'SPICES'), ('DR', 'DRINKS')], max_length=200),
        ),
    ]
