# Generated by Django 2.1.1 on 2018-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180916_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pantryitemline',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
