# Generated by Django 2.1.1 on 2018-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180916_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pantryitemline',
            name='unit',
            field=models.CharField(choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags')], max_length=20, null=True),
        ),
    ]
