# Generated by Django 2.1.1 on 2018-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180916_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
