# Generated by Django 2.1.1 on 2018-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180916_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags')], max_length=20, null=True),
        ),
    ]
