# Generated by Django 2.1.1 on 2018-09-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180916_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags'), ('Roll', 'Roll')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags'), ('Roll', 'Roll')], max_length=20, null=True),
        ),
    ]
