# Generated by Django 2.1.1 on 2018-09-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180916_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=32),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags'), ('Roll', 'Roll'), ('Tube', 'Tube'), ('Bag', 'Bag')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='size',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=32),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liter'), ('GR', 'Grams'), ('Bags', 'Bags'), ('Roll', 'Roll'), ('Tube', 'Tube'), ('Bag', 'Bag')], max_length=20, null=True),
        ),
    ]
