# Generated by Django 2.1.1 on 2018-09-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180916_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pantryitemline',
            name='unit',
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Unit'),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='pantry_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.PantryItem'),
        ),
        migrations.AlterField(
            model_name='pantryitemline',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
