# Generated by Django 2.1.1 on 2018-09-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180923_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
