# Generated by Django 2.1.1 on 2018-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180923_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='expiry_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
