# Generated by Django 2.1.1 on 2018-09-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180930_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Location'),
        ),
    ]
