# Generated by Django 2.1.1 on 2018-09-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180930_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Location'),
        ),
    ]
