# Generated by Django 2.1.2 on 2018-10-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20181007_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Category'),
        ),
    ]
